language: python
python:
    - "2.7"
    - "2.6"

install:
    - "python setup.py install"

script:
    - "python -m unittest backpy_tests.config_file"
    - "python -m unittest backpy_tests.backup"
    - "python -m unittest backpy_tests.restore"
