language: python
python:
    - "2.7"

install:
    - "python setup.py install"

script:
    - "python -m unittest -v backpy_tests.config_file_test"
    - "python -m unittest -v backpy_tests.helpers_test"
    - "python -m unittest -v backpy_tests.index_test"
    - "python -m unittest -v backpy_tests.backup_test"
    - "python -m unittest -v backpy_tests.restore_test"
