language: python
python:
    - "2.7"
    - "2.6"

install:
    - "python setup.py install"

script:
    - "python backpy_tests/config_file.py"
    - "python backpy_tests/backup.py"
    - "python backpy_tests/restore.py"
